# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.9
    
# what branches should be evaluated
branches:
    only:
        - main

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt


# a list of commands to run before the main script
#Since the feedback loop is in development some variables are assigned but not used, ignoring F841, which highlights them
before_script:
    - "flake8 --ignore=F841 cab-dynamic-pricing"

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
# We have written and run tests for all the working pricing inference code in the repository. Some of the files are placeholder 
# test files for feedback app which is in progress. It is important to note APIs aren't tested using unittest because of API key security, 
# hence the app.py has a low coverage. We try to test the interface of API in test files to validate actual modules.
after_success:
    - cd cab-dynamic-pricing
    - coverage run --source=app,model_scripts,configuration_files,tests -m unittest discover tests/
    - coverage report -m
    - coveralls
